### PR TITLE
API spec

### PR DESCRIPTION
**Pull request by jimthematrix**
- serves the Swagger UI on `/api` endpoint with the openapi 3.0 yaml
- enhanced the transaction receipt with information that got lost previously (block number, tx id, etc.)

### CODE REVIEW

**Comment by peterbroadhurst** [comment]
I rebased after merge of #64

**Review by peterbroadhurst — CHANGES_REQUESTED** [review]
Hit a few swagger validation errors on import to editor.swagger.io:

```

Errors
Hide
 
Semantic error at paths./eventstreams/{evenstreamId}
Declared path parameter "evenstreamId" needs to be defined as a path parameter at either the path or operation level
Jump to line 142
Semantic error at paths./eventstreams/{evenstreamId}.get.parameters.0.name
Path parameter "eventstreamId" must have the corresponding {eventstreamId} segment in the "/eventstreams/{evenstreamId}" path
Jump to line 146
Semantic error at components.schemas.websocket_info.properties.distributionMode.default
Default values must be present in `enum`
Jump to line 381
 
 ```

**Comment by jimthematrix** [comment]
thanks @peterbroadhurst, just pushed another commit to fix the validation errors (another tool I used apitools.dev somehow missed both)

**Review by peterbroadhurst — APPROVED** [review]
👍 

I note diligence will be required to ensure the swagger stays up to date.
Reminds me that we should pull the swagger I know has been created for EthConnect into that repo too.

**Comment by jimthematrix** [comment]
> I note diligence will be required to ensure the swagger stays up to date.
indeed. I did think about the code-based approach used in the FireFly repo to generate the Swagger, and realized that it still requires parallel maintenance alongside the implementation itself (correct me if I misunderstood). so it'd be easier to maintain the yaml directly rather than using code.

**Comment by peterbroadhurst** [comment]
It doesn't require any parallel maintenance once in place, but it would mean a migration of the routing infra.

It probably makes sense to move that API routing and swagger generation code out to a separate Go Module at this point - was something @shorsher suggested. That would make it clearer how it could be used in a project other than FireFly Core.

**Pull request merged**
