### PR TITLE
Fix event subscription when since is 0

### PR DESCRIPTION
**Pull request by jimthematrix**
Signed-off-by: Jim Zhang <jim.zhang@kaleido.io>

### CODE REVIEW

**Review by peterbroadhurst — COMMENTED** [review]
Hi @jimthematrix - just trying to understand the code here.

I notice the input `fromBlock` is a string:
https://github.com/hyperledger/firefly-fabconnect/blob/79202b6911046d75fc9ecde4418f1bd6719c6cb1/internal/events/api/event.go#L53

I assert the behaviour required is:
- If the input `fromBlock` is the empty string then subscribe from _latest_ block
- If the input `fromBlock` is the string `"0"` then subscribe from block zero

I note there seems to be a bug in FireFly where it's not specifying the `fromBlock`:
https://github.com/hyperledger/firefly/blob/ee167998727f4dceb4f56baa4f7614bfabb8ebfd/internal/blockchain/fabric/eventstream.go#L112-L121

... is there a PR up for that too?

**Comment by jimthematrix** [comment]
@peterbroadhurst think the FireFly side is indeed a bug, resulting in always subscribing to the latest block.

The current fix is independent of that, which makes the behavior consistent with the expected:
- If the input fromBlock is the empty string then subscribe from latest block
- If the input fromBlock is the string "0" then subscribe from block zero

**Review by peterbroadhurst — APPROVED** [review]
Thanks @jimthematrix - merging this, and I'll submit the fix to FireFly

**Comment by peterbroadhurst** [comment]
https://github.com/hyperledger/firefly/pull/361 raised for the FireFly bug

**Pull request merged**
